//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOM.WebInterface
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BusinessService_DBEntities : DbContext
    {
        public BusinessService_DBEntities()
            : base("name=BusinessService_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SynopticLayouts> SynopticLayouts { get; set; }
    
        [DbFunction("BusinessService_DBEntities", "F_Anomalie_Aperte2")]
        public virtual IQueryable<F_Anomalie_Aperte2_Result> F_Anomalie_Aperte2(string workplace_IN)
        {
            var workplace_INParameter = workplace_IN != null ?
                new ObjectParameter("Workplace_IN", workplace_IN) :
                new ObjectParameter("Workplace_IN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_Anomalie_Aperte2_Result>("[BusinessService_DBEntities].[F_Anomalie_Aperte2](@Workplace_IN)", workplace_INParameter);
        }
    
        public virtual ObjectResult<List_Cis_D_R_Result> List_Cis_D_R()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Cis_D_R_Result>("List_Cis_D_R");
        }
    
        public virtual ObjectResult<List_Cis_R_E_Result> List_Cis_R_E()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<List_Cis_R_E_Result>("List_Cis_R_E");
        }
    
        public virtual int PlantModelTree()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PlantModelTree");
        }
    
        public virtual ObjectResult<SP_F_TOP_TRANSITO_Result> SP_F_TOP_TRANSITO(string workplace_IN)
        {
            var workplace_INParameter = workplace_IN != null ?
                new ObjectParameter("Workplace_IN", workplace_IN) :
                new ObjectParameter("Workplace_IN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_F_TOP_TRANSITO_Result>("SP_F_TOP_TRANSITO", workplace_INParameter);
        }
    }
}
