//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOM.WebInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynopticData
    {
        public string ElementId { get; set; }
        public string SynopticLayout { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public int Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
